apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
    visualize: "true"
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
        visualize: "true"
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379
