apiVersion: v1
kind: ReplicationController
metadata:
  name: aggregator
spec:
  template:
    metadata:
      labels:
        app: aggregator
        track: alpha
    spec:
      containers:
      - name: aggregator
        image: gcr.io/ultimate-hydra-87508/aggregator:2016-03-08-cb744cd
        command:
        - /aggregator
        - -selector=run=vegeta
        - -use-ip=true
        - -sleep=1s
        - -address=0.0.0.0:8080
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
      dnsPolicy: ClusterFirst
