apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 0
  template:
    metadata:
      labels:
        run: nginx
        color: "003F3F"
        visualize: "true"
    spec:
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-scale:0.2
        resources:
          requests:
            cpu: 100m
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
