apiVersion: v1
kind: ReplicationController
metadata:
  name: vegeta
spec:
  replicas: 0
  template:
    metadata:
      labels:
        run: vegeta
        color: "00003F"
        visualize: "true"
    spec:
      containers:
      - name: vegeta
        image: gcr.io/google_containers/loader:0.4
        resources:
          requests:
            cpu: 100m
        command:
          - /loader
          - -host=nginx
          - -rate=1000
          - -address=:8080
          - -workers=10
          - -duration=1s
      dnsPolicy: ClusterFirst
